filter:
  excluded_paths:
    - 'tests/*'
    - 'features/*'

checks:
  php: true

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true

build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'

      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run