language: php

sudo: true
php:
  - '7.4'
  - '8.0'
  - '8.1'
  - nightly

env:
  global:
    - TARGET=test

matrix:
  fast_finish: true
  include:
    - php: '7.4'
      env: SYMFONY=5.4.*
    - php: '8.0'
      env: SYMFONY=5.4.*
    - php: '8.0'
      env: SYMFONY=6.0.*
    - php: '8.1'
      env: SYMFONY=5.4.*
    - php: '8.1'
      env: SYMFONY=6.0.*


  allow_failures:
    - php: nightly

install:
  - if [ -x .travis/install_${TARGET}.sh ]; then .travis/install_${TARGET}.sh; fi;

script:
  - if [ -x .travis/script_${TARGET}.sh ]; then .travis/script_${TARGET}.sh; fi;

after_success:
  - if [ -x .travis/after_success_${TARGET}.sh ]; then .travis/after_success_${TARGET}.sh; fi;
