volumes:
  composer_81: ~
  composer_81_lock: ~

services:
  php81:
    environment:
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
    build:
      context: .
      args:
        FROM_IMAGE: php:8.1-cli
    image: neimheadh/sonata-annotation-bundle:php-8.1
    volumes:
      - .:/var/www
    working_dir: /var/www

  php82:
    environment:
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
    build:
      context: .
      args:
        FROM_IMAGE: php:8.2-cli
    image: neimheadh/sonata-annotation-bundle:php-8.2
    volumes:
      - .:/var/www
    working_dir: /var/www