volumes:
  composer_74: ~
  composer_74_lock: ~
  composer_80: ~
  composer_80_lock: ~
  composer_81: ~
  composer_81_lock: ~

services:
  php74:
    environment:
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
    build:
      context: .
      args:
        FROM_IMAGE: php:7.4-cli
        XDEBUG_VERSION: '-3.1.3'
    image: neimheadh/sonata-annotation-bundle:php-7.4
    volumes:
      - .:/var/www
    working_dir: /var/www

  php80:
    environment:
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
    build:
      context: .
      args:
        FROM_IMAGE: php:8.0-cli
    image: neimheadh/sonata-annotation-bundle:php-8.0
    volumes:
      - .:/var/www
    working_dir: /var/www

  php81:
    environment:
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
    build:
      context: .
      args:
        FROM_IMAGE: php:8.1-cli
    image: neimheadh/sonata-annotation-bundle:php-8.1
    volumes:
      - .:/var/www
    working_dir: /var/www

  php82:
    environment:
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
    build:
      context: .
      args:
        FROM_IMAGE: php:8.2-cli
    image: neimheadh/sonata-annotation-bundle:php-8.2
    volumes:
      - .:/var/www
    working_dir: /var/www